"""empty message

Revision ID: 97232274dce5
Revises: 37f4922733bd
Create Date: 2023-10-06 16:46:50.222272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97232274dce5'
down_revision = '37f4922733bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
